enum Events {
  HAS_AUTHORIZED = 'BEARER_HAS_AUTHORIZED',
  AUTHORIZED = 'BEARER_AUTHORIZED',
  SESSION_INITIALIZED = 'BEARER_SESSION_INITIALIZED',
  SCENARIO_AUTHORIZED = 'BEARER_SCENARIO_AUTHORIZED',
  SCENARIO_REVOKED = 'BEARER_SCENARIO_REVOKED'
}

export default Events
